version: "3.8"
services:
  data-model-mapper-gui:
    image: data-model-mapper-gui
    build:
      context: .
      args:
        BASE_HREF: /data-model-mapper-gui/
    ports:
      - "12345:80"
    volumes:
      - ./src/assets/config.json:/usr/share/nginx/html/assets/config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cape-network


networks:
 cape-network:
   name: data-model-mapper-gui-network
   driver: bridge
   driver_opts:
     com.docker.network.driver.mtu: 1400
